export const DISTRICT_OPTIONS = [
    { value: "Anantapur", label: "Anantapur / అనంతపురం" },
    { value: "Anakapalli", label: "Anakapalli / అనకాపల్లి" },
    { value: "Annamayya", label: "Annamayya / అన్నమయ్య" },
    { value: "Alluri Sitharama Raju", label: "Alluri Sitharama Raju / అల్లూరి సీతారామ రాజు" },
    { value: "Bapatla", label: "Bapatla / బాపట్ల" },
    { value: "Chittoor", label: "Chittoor / చిత్తూరు" },
    { value: "East Godavari", label: "East Godavari / తూర్పు గోదావరి" },
    { value: "Eluru", label: "Eluru / ఏలూరు" },
    { value: "Guntur", label: "Guntur / గుంటూరు" },
    { value: "Kakinada", label: "Kakinada / కాకినాడ" },
    { value: "Konaseema", label: "Konaseema / కొనసీమ" },
    { value: "Krishna", label: "Krishna / కృష్ణా" },
    { value: "Kurnool", label: "Kurnool / కర్నూలు" },
    { value: "Nandyal", label: "Nandyal / నంద్యాల" },
    { value: "NTR District", label: "NTR District / ఎన్‌టిఆర్ జిల్లా" },
    { value: "Palnadu", label: "Palnadu / పల్నాడు" },
    { value: "Parvathipuram Manyam", label: "Parvathipuram Manyam / పర్వతీపురం మన్యం" },
    { value: "Prakasam", label: "Prakasam / ప్రకాశం" },
    { value: "Sri Potti Sriramulu Nellore", label: "Sri Potti Sriramulu Nellore / శ్రీ పొట్టి శ్రీరాములు నెల్లూరు" },
    { value: "Sri Sathya Sai", label: "Sri Sathya Sai / శ్రీ సత్య సాయి" },
    { value: "Srikakulam", label: "Srikakulam / శ్రీకాకుళం" },
    { value: "Tirupati", label: "Tirupati / తిరుపతి" },
    { value: "Visakhapatnam", label: "Visakhapatnam / విశాఖపట్నం" },
    { value: "Vizianagaram", label: "Vizianagaram / విజయనగరం" },
    { value: "West Godavari", label: "West Godavari / పడమటి గోదావరి" },
    { value: "YSR Kadapa", label: "YSR Kadapa / వైఎస్ఆర్ కడప" }
  ];
  